CREATE TABLE SPRINGDB.TBL_PRODUCT (
	PNO NUMBER,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(100 )NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGD8 DATE DEFAULT sysdate,
	READCOUNT NUMBER DEFAYKT 0,
	IMGFILE VARCHAR(2000),
	MODD8 DATE DEFAULT sysdate
);

ALTER TABLE SPRINGDB.TBL_PRODUCT
ADD CONSTRAINT TBL_PRODUCT_PK PRIMARY KEY (PNO)
ENABLE;

CREATE SEQUENCE SEQ_PRODUCT INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;